name: Branch Based CI



on:
  push:
    branches:
      - main
      - develop


jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Show branch
        run:  echo "Runnning on branch $GITHUB_REF_NAME"



  build:
    needs: test
    if: github.ref == 'refs/heads/develop' || github.ref == 'refs/heads/main'
    environment: development
    runs-on: ubuntu-latest
    steps:
      - name: Build application
        run: echo "Building application..."

      - name: Show environment
        run: echo "Environment is $APP_ENV"
