name: Call Reusable Workflow

on:
  workflow_dispatch:

jobs:
  call-build:
    uses: ./.github/workflows/reusable-build.yml
    with:
      environment: production


    show-version:
    needs: call-build
    runs-on: ubuntu-latest

    steps:
      - name: Show app version
        run: echo "Application version is ${{ needs.call-build.outputs.app-version }}"
