

name: My First CI


on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: code checkout
        uses: actions/checkout@v4
      - name: Show files
         run: echo "Hello from GitHub Actions"
