name: My First CI

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "Hello from My First CI"
      - run: pwd
      - run: ls
      - name: Step 1
        run: echo "I am Step 1"

      - name: Step 2
        run: echo "I am Step 2"

      - name: Step 3
        run: echo "I am Step 3"
      
      - name: Success check
        if: success()
        run: echo "SUCCESS condition is true"

      - name: Failure check
        if: failure()
        run: echo "FAILURE condition is true" 
        
        


      
        
        
      
      
        
        
      - run: bash 02-memory-health-checker/memory_checker.sh  
