name: My First CI

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "Hello from My First CI"
      - run: pwd
      - run: ls  
      - run: bash 02-memory-health-checker/memory_checker.sh
      - run: exit 1 
