name: Concurrency Demo

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Start
        run: echo "Workflow started"

      - name: Wait
        run: sleep 30

      - name: Finish
        run: echo "Workflow finished"
