name: Reusable Build

on:
  workflow_call:

   inputs:
    environment:
     required: true
     type: string






jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Show environment
        run: echo "Building for ${{ inputs.environment }}"


      - name: Build application
        run: echo "Building application..."

      - name: Run tests
        run: echo "Running tests..."
