name: Reusable Build

on:
  workflow_call:

   inputs:
    environment:
     required: true
     type: string

   outputs:
     app-version:
       description: "Application version"
       value: ${{ jobs.build.outputs.version }}





jobs:
  build:
    runs-on: ubuntu-latest

    outputs:
      version: ${{ steps.version.outputs.version }}


    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Show environment
        run: echo "Building for ${{ inputs.environment }}"


      - name: Build application
        run: echo "Building application..."

      - name: Run tests
        run: echo "Running tests..."

      - name: Generate version
        id: version
        run: echo "version=1.0.5" >> "$GITHUB_OUTPUT"
